const actionsTypes = {
  UPDATE_SEARCH_RESULTS_POPULAR: 'UPDATE_SEARCH_RESULTS_POPULAR',
  UPDATE_SEARCH_RESULTS_TOP_RATED: 'UPDATE_SEARCH_RESULTS_TOP_RATED',
  UPDATE_SEARCH_RESULTS_CUSTOM: 'UPDATE_SEARCH_RESULTS_CUSTOM',
  CLEAR_SEARCH_RESULTS_CUSTOM: 'CLEAR_SEARCH_RESULTS_CUSTOM',
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_IS_FETCHING_EPISODE: 'SET_IS_FETCHING_EPISODE',
  SET_NUM_SEASONS: 'SET_NUM_SEASONS',
  SET_NUM_EPISODES: 'SET_NUM_EPISODES',
  SET_RANDOM_EPISODE: 'SET_RANDOM_EPISODE',
};

export default actionsTypes;
