const actionsTypes = {
  UPDATE_SEARCH_RESULTS_POPULAR: 'UPDATE_SEARCH_RESULTS_POPULAR',
  UPDATE_SEARCH_RESULTS_TOP_RATED: 'UPDATE_SEARCH_RESULTS_TOP_RATED',
  UPDATE_SEARCH_RESULTS_CUSTOM: 'UPDATE_SEARCH_RESULTS_CUSTOM',
}

export default actionsTypes;