const actionsTypes = {
  UPDATE_SEARCH_RESULTS_POPULAR: 'UPDATE_SEARCH_RESULTS_POPULAR',
  UPDATE_SEARCH_RESULTS_TOP_RATED: 'UPDATE_SEARCH_RESULTS_TOP_RATED',
  UPDATE_SEARCH_RESULTS_CUSTOM: 'UPDATE_SEARCH_RESULTS_CUSTOM',
  SET_IS_LOADING: 'SET_IS_LOADING',
};

export default actionsTypes;
