const actionsTypes = {
  UPDATE_SEARCH_RESULTS: 'UPDATE_SEARCH_RESULTS',
  CLEAR_SEARCH_RESULTS_CUSTOM: 'CLEAR_SEARCH_RESULTS_CUSTOM',
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_IS_FETCHING_EPISODE: 'SET_IS_FETCHING_EPISODE',
  SET_NUM_SEASONS: 'SET_NUM_SEASONS',
  SET_NUM_EPISODES: 'SET_NUM_EPISODES',
  SET_RANDOM_EPISODE: 'SET_RANDOM_EPISODE',
  SAVE_EPISODE_DATA: 'SAVE_EPISODE_DATA',
  SET_ACTIVE_SHOW: 'SET_ACTIVE_SHOW',
  CLEAR_ACTIVE_SHOW: 'CLEAR_ACTIVE_SHOW',
  ADD_SEASON_DETAILS: 'ADD_SEASON_DETAILS',
};

export default actionsTypes;
